build: Adds option to install kernel and image
If a user pulls down cc-oci-runtime and does a make install, Clear
Containers will not work. It is assumed that binary artifacts are
already installed.

This adds `artifacts` option to the makefile, this option will
download and install clear containers kernel and clear containers
image.

Fixes: #912

Signed-off-by: Geronimo Orozco <geronimo.orozco@intel.com>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -818,6 +818,26 @@ endif
 
 check: $(CHECK_DEPS)
 
+artifacts: | install-image install-kernel
+
+# Get clear containers image path
+IMAGE_PATH := $(shell dirname $(CONTAINERS_IMG))
+install-image:
+	@if [ $(shell id -u) -ne 0 ]; then \
+		$(srcdir)/installation/install_clear_image.sh $(CLEAR_VM_IMAGE_VERSION) $(IMAGE_PATH) ; \
+	else \
+		>&2 echo "ERROR: do not run $@ as root" ; \
+	fi
+
+# Get clear containers kernel path
+KERNEL_PATH := $(shell dirname $(CONTAINER_KERNEL))
+install-kernel:
+	@if [ $(shell id -u) -ne 0 ]; then \
+		$(srcdir)/installation/install_clear_kernel.sh $(CLEAR_VM_IMAGE_VERSION) $(CLEAR_VM_KERNEL_VERSION) $(KERNEL_PATH) ; \
+	else \
+		>&2 echo "ERROR: do not run $@ as root" ; \
+	fi
+
 clean-local:
 	rm -f commit_id
 if AUTOGOPATH
