If a test fails, don't remove its logs - instead show their location.
Signed-off-by: James Hunt <james.o.hunt@intel.com>

diff --git a/tests/functional/common.bash.in b/tests/functional/common.bash.in
--- a/tests/functional/common.bash.in
+++ b/tests/functional/common.bash.in
@@ -179,8 +179,12 @@ function setup_common(){
 
 # Cleanup anything generated by this script
 function cleanup_common(){
-	if [ -d "$COR_ROOT_DIR" ]
-	then
-		rm -r "$COR_ROOT_DIR"
-	fi
+    if [ "$BATS_ERROR_STATUS" -eq 1 ]
+    then
+        # XXX: retain logs if tests fail
+        echo "Test logs: $COR_ROOT_DIR" >&2
+        return
+    fi
+
+    rm -rf "$COR_ROOT_DIR"
 }
