Tests: Fix whitespace.
Signed-off-by: James Hunt <james.o.hunt@intel.com>

diff --git a/tests/functional/common.bash.in b/tests/functional/common.bash.in
--- a/tests/functional/common.bash.in
+++ b/tests/functional/common.bash.in
@@ -24,7 +24,7 @@ COR_BINARY="${BATS_TEST_DIRNAME}/../../cc-oci-runtime"
 
 # Make temporal tests directory
 function mktemp_tests_dir(){
-       mktemp -d --tmpdir="$BATS_TMPDIR" --suffix=-cor-test
+	mktemp -d --tmpdir="$BATS_TMPDIR" --suffix=-cor-test
 }
 
 # Test data dir.
@@ -45,7 +45,7 @@ function check_ccontainers() {
 
 	local out=$(@QEMU_PATH@ -machine help | grep -o pc-lite | tail -1)
 	[ "$out" = "pc-lite" ] || \
-        skip "@QEMU_PATH@ does not have pc-lite support"
+		skip "@QEMU_PATH@ does not have pc-lite support"
 
 	if [ ! -d "$BUNDLE_DIR" ]
 	then
@@ -233,28 +233,28 @@ function setup_common(){
 
 # Cleanup anything generated by this script
 function cleanup_common(){
-    if [ "$BATS_ERROR_STATUS" -eq 1 ]
-    then
-        echo >&2 "Test logs: $COR_ROOT_DIR"
-        echo >&2 "Global log file: $COR_LOG_FILE"
-        echo >&2 "Hypervisor log dir: $COR_HYPERVISOR_LOG_DIR"
-        echo >&2 "bats status: $status"
-        echo >&2 "bats output (lines array contains ${#lines[*]} lines):"
+	if [ "$BATS_ERROR_STATUS" -eq 1 ]
+	then
+		echo >&2 "Test logs: $COR_ROOT_DIR"
+		echo >&2 "Global log file: $COR_LOG_FILE"
+		echo >&2 "Hypervisor log dir: $COR_HYPERVISOR_LOG_DIR"
+		echo >&2 "bats status: $status"
+		echo >&2 "bats output (lines array contains ${#lines[*]} lines):"
 
-        local i=0
-        local line
+		local i=0
+		local line
 
-	for line in ${lines[@]}
-	do
-		echo >&2 "lines[$i]: '$line'"
-		i=$((i+1))
-	done
+		for line in ${lines[@]}
+		do
+			echo >&2 "lines[$i]: '$line'"
+			i=$((i+1))
+		done
 
-        # XXX: retain logs if tests fail
-        return
-    fi
+		# XXX: retain logs if tests fail
+		return
+	fi
 
-    rm -rf "$COR_ROOT_DIR" "$COR_GLOBAL_DIR"
+	rm -rf "$COR_ROOT_DIR" "$COR_GLOBAL_DIR"
 }
 
 if [ ! -e "$COR_BINARY" ]
@@ -262,5 +262,5 @@ then
 	cat <<EOT >&2
 ERROR: you need run 'make' before running the functional tests.
 EOT
-    exit 1
+	exit 1
 fi
